# Generated by Django 2.0.3 on 2019-07-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='price_large',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='platter',
            old_name='price_large',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='price_large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price_small',
        ),
        migrations.RemoveField(
            model_name='platter',
            name='price_small',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price_small',
        ),
    ]
