# Generated by Django 2.0.3 on 2019-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190727_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='platter',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.FloatField(),
        ),
    ]
